language: node_js
node_js:
  - 'iojs'
before_script: 'bin/travis-before'
after_script: 'codeclimate < coverage/lcov.info'
sudo: false
env:
  - CODECLIMATE_REPO_TOKEN=3e808e09f4950d80011b4a4d3ffb8bdb144945c780b85cb0aca2e1e945568832
branches:
  only:
    - master
    - staging
    - dev
notifications:
  email: false